version: '3'

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    # environment:
    #   - MONGO_HOST=${MONGO_HOST}
    #   - MONGO_PORT=${MONGO_PORT}
    volumes:
      - ./data/app:/data/db
    depends_on:
      - mongo
      - redis

  mongo:
    image: 'mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27018:27017
  mongo_express:
      image: 'mongo-express'
      container_name: mongo_express
      depends_on:
          - 'mongo'
      ports:
          - '12345:8081'
      restart: always
  redis:
    image: 'redis'
    restart: always
