version: '3'

services:
  app:
    build: .
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
    volumes:
      - ./data/mongo:/data/db
    # ports:
    #   - 27018:27017
  redis:
    image: redis:6.2.3-alpine
    restart: always
