version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongo:27017/mongodb
      REDIS_ADDR: redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4.6-bionic
    restart: always
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:6.2.3-alpine
    restart: always
